# Generated by Django 2.2.6 on 2019-11-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('kmsPista', models.IntegerField(max_length=10)),
                ('numeroRemontes', models.IntegerField(max_length=10)),
                ('alturaMaxima', models.IntegerField(max_length=10)),
                ('alturaMinima', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionToTipoPista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPistas', models.IntegerField(max_length=10)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Estacion')),
                ('tipoPista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.TipoPista')),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Localizacion'),
        ),
    ]
