# Generated by Django 2.2.6 on 2019-11-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20191105_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='detalles',
            field=models.CharField(max_length=255),
        ),
    ]
