# Generated by Django 2.0 on 2019-11-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20191120_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionToUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='estaciontousuario',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Estacion'),
        ),
        migrations.AddField(
            model_name='estaciontousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Usuario'),
        ),
    ]
